version: '3.8'

services:
  app:
    build: .
    container_name: decluster-container
    volumes:
      - .:/app  
      - node_modules:/app/node_modules  
      - client_node_modules:/app/client/node_modules 
    ports:
      - "8080:8080"
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
    command: npm run start

  redis:
    image: "redis:alpine"
    container_name: my_redis_container
    ports:
      - "6379:6379"

volumes:
  node_modules:
  client_node_modules:
