name: CI Pipeline

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: Clean npm cache and install root dependencies
      run: |
        npm cache clean --force
        rm -rf node_modules package-lock.json
        npm install --legacy-peer-deps

    - name: Clean and install client dependencies
      run: |
        cd client
        rm -rf node_modules package-lock.json
        npm cache clean --force
        npm install --legacy-peer-deps

    - name: Run tests
      run: npm test

    - name: Build client
      run: cd client && npm run build
